import { PrismaClient, ProductCategory, Region, Season } from "@prisma/client";

// Create a new PrismaClient instance
const prisma = new PrismaClient();

async function main() {
  console.log("Starting seeding...");

  // Use the specific organization ID provided
  const orgId = "cm988a43z0002k8bjzudn0auf";

  // Verify that the organization exists
  const organization = await prisma.organization.findUnique({
    where: { id: orgId },
  });

  if (!organization) {
    console.error(`Organization with ID ${orgId} not found. Aborting seed.`);
    return;
  }

  console.log(`Found organization: ${organization.name}`);

  // Sample product data
  const products = [
    {
      name: "Wireless Headphones",
      description: "High-quality wireless headphones with noise cancellation",
      category: ProductCategory.Electronics,
      subCategory: "Audio",
      season: Season.Winter,
      region: Region.North,
      warehouseId: 1,
      leadtime: 5,
      supplierReliability: 0.9,
      transportCost: 15.0,
      promotion: 10.0,
      brand: "TechAudio",
      stock: 100,
      reorderPoint: 20,
      supplierAddress: "123 Supplier St, City, Country",
      supplierName: "TechSuppliers Inc",
      supplierContact: "+1-555-123-4567",
      sellingPrice: 199.99,
      costPrice: 120.00,
      taxRate: 10.0,
      weight: 250.0,
      dimensions: "20x15x5",
      isActive: true,
      isFeatured: true,
      image:
        "https://unsplash.com/photos/flatlay-photography-of-wireless-headphones-PDX_a_82obo",
      organizationId: orgId,
    },
    {
      name: "Organic Coffee Beans",
      description: "Premium organic coffee beans from sustainable farms",
      category: ProductCategory.Beverages,
      subCategory: "Coffee",
      season: Season.Summer,
      region: Region.South,
      warehouseId: 2,
      leadtime: 3,
      supplierReliability: 0.85,
      transportCost: 8.0,
      promotion: 5.0,
      brand: "GreenBean",
      stock: 200,
      reorderPoint: 50,
      supplierAddress: "456 Coffee Ave, City, Country",
      supplierName: "Coffee Suppliers Ltd",
      supplierContact: "+1-555-987-6543",
      sellingPrice: 24.99,
      costPrice: 15.00,
      taxRate: 8.0,
      weight: 500.0,
      dimensions: "10x10x5",
      isActive: true,
      isFeatured: false,
      image:
        "https://unsplash.com/photos/brown-coffee-beans-in-clear-glass-jar-5U_28ojjgms",
      organizationId: orgId,
    },
    {
      name: "Smart Watch",
      description: "Feature-rich smartwatch with health monitoring",
      category: ProductCategory.Electronics,
      subCategory: "Wearables",
      season: Season.Monsoon,
      region: Region.East,
      warehouseId: 1,
      leadtime: 7,
      supplierReliability: 0.95,
      transportCost: 12.0,
      promotion: 15.0,
      brand: "SmartTech",
      stock: 75,
      reorderPoint: 15,
      supplierAddress: "789 Tech Blvd, City, Country",
      supplierName: "TechGadgets Inc",
      supplierContact: "+1-555-456-7890",
      sellingPrice: 299.99,
      costPrice: 180.00,
      taxRate: 12.0,
      weight: 50.0,
      dimensions: "5x5x1",
      isActive: true,
      isFeatured: true,
      image:
        "https://unsplash.com/photos/person-wearing-black-smartwatch-8qEB0fTe9Vw",
      organizationId: orgId,
    },
    {
      name: "Organic Rice",
      description: "Premium organic rice from sustainable farms",
      category: ProductCategory.Grocery,
      subCategory: "Grains",
      season: Season.Monsoon,
      region: Region.West,
      warehouseId: 3,
      leadtime: 4,
      supplierReliability: 0.8,
      transportCost: 10.0,
      promotion: 0.0,
      brand: "GreenHarvest",
      stock: 500,
      reorderPoint: 100,
      supplierAddress: "321 Farm Rd, City, Country",
      supplierName: "Organic Farms Co",
      supplierContact: "+1-555-789-0123",
      sellingPrice: 19.99,
      costPrice: 12.00,
      taxRate: 5.0,
      weight: 2000.0,
      dimensions: "30x20x10",
      isActive: true,
      isFeatured: false,
      image:
        "https://unsplash.com/photos/white-rice-in-clear-glass-container-8Nc_oIPsc1Q",
      organizationId: orgId,
    },
    {
      name: "Raw Cotton",
      description: "High-quality raw cotton for textile manufacturing",
      category: ProductCategory.RawMaterials,
      subCategory: "Textiles",
      season: Season.Summer,
      region: Region.South,
      warehouseId: 4,
      leadtime: 10,
      supplierReliability: 0.75,
      transportCost: 25.0,
      promotion: 0.0,
      brand: "CottonFields",
      stock: 1000,
      reorderPoint: 200,
      supplierAddress: "654 Cotton Ln, City, Country",
      supplierName: "Textile Materials Ltd",
      supplierContact: "+1-555-234-5678",
      sellingPrice: 5.99,
      costPrice: 3.50,
      taxRate: 7.0,
      weight: 5000.0,
      dimensions: "50x30x20",
      isActive: true,
      isFeatured: false,
      image: "https://unsplash.com/photos/white-cotton-fabric-8Nc_oIPsc1Q",
      organizationId: orgId,
    },
    // 5 additional products
    {
      name: "Laptop Pro",
      description: "High-performance laptop for professionals",
      category: ProductCategory.Electronics,
      subCategory: "Computers",
      season: Season.Winter,
      region: Region.North,
      warehouseId: 1,
      leadtime: 8,
      supplierReliability: 0.92,
      transportCost: 20.0,
      promotion: 5.0,
      brand: "TechPro",
      stock: 50,
      reorderPoint: 10,
      supplierAddress: "789 Tech Park, City, Country",
      supplierName: "TechDistributors Inc",
      supplierContact: "+1-555-345-6789",
      sellingPrice: 1299.99,
      costPrice: 900.00,
      taxRate: 10.0,
      weight: 2000.0,
      dimensions: "35x25x2",
      isActive: true,
      isFeatured: true,
      image: "https://unsplash.com/photos/silver-macbook-pro-on-table-4hbJ-eymZ1o",
      organizationId: orgId,
    },
    {
      name: "Green Tea",
      description: "Premium Japanese green tea",
      category: ProductCategory.Beverages,
      subCategory: "Tea",
      season: Season.Summer,
      region: Region.East,
      warehouseId: 2,
      leadtime: 4,
      supplierReliability: 0.88,
      transportCost: 7.0,
      promotion: 0.0,
      brand: "TeaLeaf",
      stock: 300,
      reorderPoint: 60,
      supplierAddress: "123 Tea Garden, City, Country",
      supplierName: "Tea Importers Co",
      supplierContact: "+1-555-567-8901",
      sellingPrice: 14.99,
      costPrice: 8.00,
      taxRate: 5.0,
      weight: 100.0,
      dimensions: "15x10x5",
      isActive: true,
      isFeatured: false,
      image: "https://unsplash.com/photos/green-tea-leaves-in-clear-glass-container-8Nc_oIPsc1Q",
      organizationId: orgId,
    },
    {
      name: "Steel Pipes",
      description: "High-quality steel pipes for construction",
      category: ProductCategory.RawMaterials,
      subCategory: "Construction",
      season: Season.Monsoon,
      region: Region.West,
      warehouseId: 4,
      leadtime: 12,
      supplierReliability: 0.78,
      transportCost: 30.0,
      promotion: 0.0,
      brand: "SteelWorks",
      stock: 800,
      reorderPoint: 150,
      supplierAddress: "456 Industrial Park, City, Country",
      supplierName: "Steel Manufacturers Ltd",
      supplierContact: "+1-555-678-9012",
      sellingPrice: 45.99,
      costPrice: 30.00,
      taxRate: 8.0,
      weight: 10000.0,
      dimensions: "200x10x10",
      isActive: true,
      isFeatured: false,
      image: "https://unsplash.com/photos/metal-pipes-8Nc_oIPsc1Q",
      organizationId: orgId,
    },
    {
      name: "Organic Honey",
      description: "Pure organic honey from local beekeepers",
      category: ProductCategory.Grocery,
      subCategory: "Sweeteners",
      season: Season.Summer,
      region: Region.South,
      warehouseId: 3,
      leadtime: 3,
      supplierReliability: 0.82,
      transportCost: 6.0,
      promotion: 10.0,
      brand: "BeeSweet",
      stock: 150,
      reorderPoint: 30,
      supplierAddress: "789 Honey Farm, City, Country",
      supplierName: "Local Beekeepers Co-op",
      supplierContact: "+1-555-789-0123",
      sellingPrice: 12.99,
      costPrice: 7.50,
      taxRate: 5.0,
      weight: 500.0,
      dimensions: "10x10x15",
      isActive: true,
      isFeatured: true,
      image: "https://unsplash.com/photos/honey-in-glass-jar-8Nc_oIPsc1Q",
      organizationId: orgId,
    },
    {
      name: "General Purpose RF Module",
      description: "RF module for wireless communication",
      category: ProductCategory.GeneralRF,
      subCategory: "Communication",
      season: Season.Winter,
      region: Region.North,
      warehouseId: 1,
      leadtime: 6,
      supplierReliability: 0.87,
      transportCost: 9.0,
      promotion: 0.0,
      brand: "RF Tech",
      stock: 200,
      reorderPoint: 40,
      supplierAddress: "321 Electronics Ave, City, Country",
      supplierName: "RF Components Inc",
      supplierContact: "+1-555-890-1234",
      sellingPrice: 29.99,
      costPrice: 18.00,
      taxRate: 8.0,
      weight: 50.0,
      dimensions: "5x3x1",
      isActive: true,
      isFeatured: false,
      image: "https://unsplash.com/photos/electronic-circuit-board-8Nc_oIPsc1Q",
      organizationId: orgId,
    },
  ];

  // Insert products
  for (const product of products) {
    const result = await prisma.product.create({
      data: product,
    });
    console.log(`Created product with ID: ${result.id}`);
  }

  console.log("Seeding finished.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
